exclude: [config.rb, sass]
name: JSconf.eu
url:  http://2013.jsconf.eu
speaker_map_base_url: "http://maps.googleapis.com/maps/api/staticmap?size=640x163&scale=2&sensor=false&zoom=5&visual_refresh=1&markers=color:"
speaker_index_base_url: "http://maps.googleapis.com/maps/api/staticmap?size=514x324&sensor=false&visual_refresh=1&markers=color:"
